site_name: MOTES Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Explanation: explanation.md
  - Reference (motes.common): reference-common.md
  - Reference (motes.startup): reference-startup.md
  - Reference (motes.harvester): reference-harvester.md
