site_name: MOTES Documentation
repo_url: "https://github.com/tseccull/motes"
site_description: "Documentation for the MOTES project"
site_author: "Tom Seccull; Dominik Kiersz"

theme:
  name: "material"
  locale: en
  palette:
    primary: "blue"
    accent: "light-blue"
  font:
    text: "Roboto"
    code: "Roboto Mono"

markdown_extensions:
    - smarty # https://python-markdown.github.io/extensions/smarty/
    - toc:
        permalink: True

plugins:
  - mkdocstrings:
      default_handler: python # The handler to use for markdown generation
      handlers:
        python:
          paths: [src]
          recursive: true
          options:
            docstring_style: google # The docstring style to use
            show_source: true 

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Reference: 
    - Reference (motes.core): reference-core.md
    - Reference (motes.startup): reference-startup.md
    - Reference (motes.common): reference-common.md
    - Reference (motes.harvester): reference-harvester.md
