name: Welcome First Issue or PR

on:
  pull_request_target:
    types:
    - opened
  issues:
    types:
    - opened

jobs:
  welcome:
    runs-on: ubuntu-latest

    steps:
    - name: Welcome for First Issue or Pull Request
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >-
          ### :wave: Welcome! Looks like this is your first issue for MOTES!
          Thanks for your contribution! We will review it as soon as possible. 😄
        pr-message: >-
          ### :wave: Welcome! Looks like this is your first pull request for MOTES!
          Thanks for your contribution! We will review it as soon as possible. 😄