name: Label Pull Requests

on:
  schedule:
    - cron: "0 20 * * *"
  pull_request:
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label Job
    steps:
      - name: Add size label
        uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/XS"
          xs_max_size: "25"
          s_label: "size/S"
          s_max_size: "100"
          m_label: "size/M"
          m_max_size: "500"
          l_label: "size/L"
          l_max_size: "1000"
          xl_label: "size/XL"
          fail_if_xl: "false"
          message_if_xl: |-
            This PR has too many changes. Please address one issue/feature per PR.
            Note this PR might be rejected due to its size.
          files_to_ignore: ""

      - name: Add enhancement label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.head_ref, 'feature') }}
        with:
          labels: "enhancement"
      - name: Add bug label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.head_ref, 'bug') }}
        with:
          labels: "bug"
