name: Motes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Job - ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"] # Make sure to keep this updated. New version cycles around October for Python.
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install linting requirements
        run: |
          python -m pip install --upgrade pip
          pip install .[lint]

       # Exit-zero treats all remaining errors as warnings (for now).
      - name: Linting check with flake8
        run: |
          python -m flake8 src --config=pyproject.toml

      - name: Static code analysis with pylint
        run: |
          python -m pylint src --fail-under=8.0

      - name: Vulnerability checks with Bandit
        run: |
          python -m bandit -r src

      - name: Formatting check with Black
        run: |
          python -m black --check src