name: Motes
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Job - ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"] # Make sure to keep this updated. New version cycles around October for Python.
    steps:
      - uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        shell: bash -l {0}
        run: |
          pip install flake8 pylint bandit black

      - name: Linting check with flake8
        shell: bash -l {0}
        run: |
          python -m flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          python -m flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Static code analysis with pylint
        shell: bash -l {0}
        run: |
          python -m pylint src --fail-under=6.0

      - name: Vulnerability checks with Bandit
        shell: bash -l {0}
        run: |
          python -m bandit -r src

      - name: Formatting check with Black
        shell: bash -l {0}
        run: |
          python -m black --check src
